### ISSUE TITLE
Documentation is not clear when it comes to cuda requirements

### ISSUE THREAD

**Issue by 5cat** [nebuly-ai/nos#22]
MPS requires at least CUDA 11.5 https://developer.nvidia.com/blog/revealing-new-features-in-the-cuda-11-5-toolkit , with CUDA version less than that, the MPS server hangs and does not serve any requests.

**Comment by Telemaco019** [comment]
Hi @5cat, thanks for diving into the doc and raising the issue, much appreciated! 

You are right, MPS allows setting memory limits on individual clients starting from CUDA 11.5. However, MPS should be supported on all GPUs with compute capability 3.5 or higher (see [here](https://docs.nvidia.com/deploy/mps/index.html#topic_3_3_1_1)), so I'd expect older versions of CUDA to work as well, only without clients memory limits. 

MPS server hanging without serving requests is an unexpected behaviour. This generally happens when the client connects to the server using a different user ID (by default clients should run with UID 1000). Could you please share more information about your setup when encountering this issue?

Nevertheless, I agree the doc needs to be updated. Thank you for the PR, I'll review it soon!

**Comment by 5cat** [comment]
I was using EKS with a node AMI of `amazon-eks-gpu-node-1.25-v20230304` which has CUDA version of `11.4`.

The nebuly mps server image hanged with that cuda version despite me not requesting an MPS partition, and despite setting the `mps.userID` to `1000` and my pod spec as
```yaml
      hostIPC: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
```
The server kept hanging.
I tried user and group id of `0` and still the issue of the hanging thingy persist.

After replacing the image in [mps.image.repository](https://github.com/nebuly-ai/k8s-device-plugin/blob/main/deployments/helm/nvidia-device-plugin/values.yaml#L64) to docker.io/nvidia/mps I didnt see any hangings.

I sshed manually into the node and updated CUDA to 11.6 and restarted the daemons and everything, confirmed the version via `nvidia-smi` and manually setting `CUDA_MPS_PINNED_DEVICE_MEM_LIMIT` to `0=1G` with a resource `nvidia.com/gpu: 1` I confirmed that the limit is enforced at CUDA since I couldint get over 1025MB for the process usage. And now I assume whenever nos gpu-partitioner create a partition, things will work on the 11.6

Getting back to the hanging problem, I tried debugging the problem further using this [image](https://github.com/nebuly-ai/k8s-device-plugin/blob/main/deployments/mps-server/entrypoint.sh) but I couldint find the reason for the hanging. Both the controler and the server are giving some output, but they just stop and my process hangs where even a `ctrl+c` is not enough to kill the process that is using the gpu on the testing container. Didnt spend the time on why the docker.io/nvidia/mps did not hang while ghcr.io/nebuly-ai/nvidia-mps-server but I can say there are some differences that im not aware of in them.

I got very similar result to https://forums.developer.nvidia.com/t/mps-client-hangs/111727 although not duplicated that many times, what gave me a hint of the issue is this https://github.com/awslabs/aws-virtual-gpu-device-plugin/issues/23#issue-1178880544 where it was mentioned `CUDA_MPS_PINNED_DEVICE_MEM_LIMIT` is only supported on 11.5+ CUDA so I upgraded it and everything worked.

**Comment by Telemaco019** [comment]
Thank you for your insights, they're extremely helpful.  I've noticed that the image [docker.io/nvidia/mps](https://github.com/NVIDIA/nvidia-docker/wiki/MPS-(EXPERIMENTAL)) directly starts an MPS Server instance in its entrypoint, while Nebuly's [MPS image](https://github.com/nebuly-ai/k8s-device-plugin/blob/main/deployments/mps-server/entrypoint.sh) uses the MPS Control Daemon for spawning MPS Servers at runtime. 

My guess is that the hanging problem is related to the Control Daemon, which queues your requests without ever serving them. This also happens when Pods running with different users request MPS resources on the same GPU, as described in https://github.com/nebuly-ai/nos/issues/19.

I still have to do some more tests, but updating [ghcr.io/nebuly-ai/nvidia-mps-server](https://github.com/nebuly-ai/k8s-device-plugin/blob/main/deployments/mps-server/entrypoint.sh) and making it start the MPS server directly without the control daemon should solve both the problems. 

I'll keep you updated, thank you so much for your contribution!
