### ISSUE TITLE
wrong resource file name

### ISSUE THREAD

**Issue by WindowsXp-Beta** [nebuly-ai/nos#31]
I continued to build `gpu-agent` and found that `ts_agent.yaml` in
https://github.com/nebuly-ai/nos/blob/a32426d8d47649e91b874ffecb8df793159d7a5f/config/gpuagent/manager/kustomization.yaml#L2
was missing.
I think it should be `gpu_agent.yaml`?

**Comment by Telemaco019** [comment]
You are right, it should be `gpu_agent.yaml`. 

We did some renaming some time ago while developing the Helm chart, which created typos like this one. I'm thinking to add a step to the CI pipeline to check that all Kustomizations are at least generated correctly so that we can avoid errors like this one in the future. 

Anyway, thank you for spotting the problem! As always, if you have already fixed it and want to open a PR it is highly appreciated 😄
